### PR TITLE
Replace unless/when ... throwError with orThrowError

### PR DESCRIPTION
**Pull request by ruhatch**
The `unless condition (throwError Error)` pattern arises a lot in our code, and this replaces instances of it with ``condition `orThrowError` Error``. It also changes some `when inverseCondition` to use it too.

### CODE REVIEW

**Comment by nc6** [comment]
Personally I find this _slightly_ harder to read, since the `unless` front-loads the context that this is a condition, rather than needing to work backwards from an infix. In general, I would avoid infixing things unless the entire "clause" can be read/understood in one pass.

Having said that, if others find this more readable, I'll happily go with the majority opinion.

**Review by dnadales — APPROVED** [review]
Unlike Nick I prefer the new operator `orThrowError` over the `unless ... throwError` patterns everywhere. But as Nick said, I'm fine with whatever the majority prefers :)

**Comment by ruhatch** [comment]
I agree it might be harder to read at first. However, after reading a whole bunch of rules, and seeing the construction a few times I think it starts to pay off. To me it started to read like English, e.g. current epoch is less than delegation epoch or throw error ... Then it starts to read like a list of constraints!   How do we make a decision here?

**Comment by ruhatch** [comment]
I'm going to merge and we can always revert as it didn't take very long!

**Pull request merged**
