### PR TITLE
Remove unused crypto

### LINKED ISSUE #664: Remove unused functionality from cardano-crypto-wrapper
The `cardano-crypto-wrapper` package is only used by the ledger and dependent packages, and is not used by the wallet, which uses `cardano-crypto` directly. It derives originally from the crypto in the `cardano-sl` package.

Thus functionality for HD wallets can be removed, or split out. Furthermore: it is unclear that other functionality such as the "safe signer" abstraction is used.

The task here is to audit what is actually used used, and remove things that are not used.

### LINKED ISSUE #665: Drop dependency on scrypt package
The `scrypt` hashing function from the `scrypt` package is used in `cardano-crypto-wrapper` package as part of the `EncryptedSigningKey` type. It is used as part of a sanity-check mechanism to check that the correct decryption pass phrase is used to decrypt the signing key.

It is overkill to use `scrypt` for this purpose. If the `EncryptedSigningKey` type is needed at all (see #664) then perhaps the hash function can be replaced with our normal crypto hash function.

### PR DESCRIPTION
**Pull request by dcoutts**
The summary is that `SafeSigner` can be simplified because we do not use its special feature at all. This then unlocks a cascade of other now-unused code that we can remove, including eliminating `EncryptedSigningKey` and dropping the `scrypt` dependency.

See the individual patches for more detailed explanations. It's structured as a series of small changes so should hopefully be easy to follow.

This builds on #674 so look at the first 4 patches in the context of that PR and ignore them for this one.

Fixes #664 
Fixed #665

### CODE REVIEW

**Comment by dcoutts** [comment]
Changes needed in the node once this is merged: https://github.com/input-output-hk/cardano-node/tree/dcoutts/remove-unused-crypto

**Review by nc6 — APPROVED** [review]

**Pull request merged**
