### PR TITLE
Remove backpack

### PR DESCRIPTION
**Pull request by nc6**
This PR removes backpack from `cs-ledger`.

It didn't end up being useful, and it was blocking integration into any `stack` based project.

Also included is one random fix which removes a cabal warning!

### CODE REVIEW

**Comment by nc6** [comment]
Not immediately clear to me why hydra is failing...

**Review by mdimjasevic — COMMENTED** [review]
I've tried to start the `nix-shell` in the `specs/chain/` directory, but I got this:

```
...
No uhc found
building
Preprocessing library for cs-ledger-0.1.0.0..
Setup: can't find source for Ledger/Signatures in src, dist/build/autogen,
dist/build/global-autogen

builder for '/nix/store/ywp781h4fssh97mx6vqxbsbg3xcn2vfm-cs-ledger-0.1.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/9ksaxnkvly3hz5b4h69l39yx3dibvdv8-ghc-8.6.1-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/9ksaxnkvly3hz5b4h69l39yx3dibvdv8-ghc-8.6.1-with-packages.drv' failed
```

Can you build it with `cabal` when in `nix-shell`?

**Comment by mdimjasevic** [comment]
Furthermore, when I start the `nix-shell` in `specs/leder` and then `cabal new-repl` within it, I get this:

```
$ cabal new-repl
Resolving dependencies...
Build profile: -w ghc-8.6.1 -O1
In order, the following will be built (use -v for more details):
 - small-steps-0.1.0.0 (lib) (first run)
 - cs-ledger-0.1.0.0 (lib) (first run)
Configuring library for small-steps-0.1.0.0..
Preprocessing library for small-steps-0.1.0.0..
Building library for small-steps-0.1.0.0..
[1 of 1] Compiling Control.State.Transition ( src/Control/State/Transition.hs, /home/marko/projects/iohk/chain-spec/nc-remove-backpack/specs/dist-newstyle/build/x86_64-linux/ghc-8.6.1/small-steps-0.1.0.0/build/Control/State/Transition.o )
Configuring library for cs-ledger-0.1.0.0..
Warning: 'hs-source-dirs: src' directory does not exist.
Preprocessing library for cs-ledger-0.1.0.0..
cabal: can't find source for Ledger/Signatures in src,
/home/marko/projects/iohk/chain-spec/nc-remove-backpack/specs/dist-newstyle/build/x86_64-linux/ghc-8.6.1/cs-ledger-0.1.0.0/build/autogen,
/home/marko/projects/iohk/chain-spec/nc-remove-backpack/specs/dist-newstyle/build/x86_64-linux/ghc-8.6.1/cs-ledger-0.1.0.0/build/global-autogen

cabal: repl failed for cs-ledger-0.1.0.0.
```

**Comment by nc6** [comment]
Because I'm an idiot, probably...

**Comment by nc6** [comment]
I neglected to include the new source files.

**Review by mdimjasevic — APPROVED** [review]

**Pull request merged**
