### PR TITLE
Remove all knowledge of HD derivation in the ledger

### PR DESCRIPTION
**Pull request by dcoutts**
The ledger is not supposed to know about HD addresses. That is supposed to be transparent to the ledger and handled only by the wallet.

Of course none of the ledger rules care about HD derivation, but the library support was there and used only by the genesis block generation code. This patch removes that only use, and then all the HD derivation support code, both from the ledger and the ledger crypto support library.

See the more detailed comments on the individual patches.

### CODE REVIEW

**Comment by dcoutts** [comment]
This depends on https://github.com/input-output-hk/cardano-node/pull/280 being tested and approved so we can be sure that removing this doesn't break anything.

**Review by nc6 — APPROVED** [review]
This looks fine to me, and the referenced PRs have been passed and merged.

**Pull request merged**
