### PR TITLE
nix integration via nix-tools

### PR DESCRIPTION
**Pull request by angerman**
This adds the relevant nix integration via `nix-tools`.

The release.nix and default.nix should be good enough for hydra to build this project.

```
nix build -f default.nix cardano-binary
nix build -f default.nix cardano-crypto
nix build -f default.nix cardano-prelude
```

should build on the current system.

```
nix build -f release.nix cardano-binary.x86_64-darwin
nix build -f release.nix cardano-crypto.x86_64-darwin
nix build -f release.nix cardano-prelude.x86_64-darwin
nix build -f release.nix cardano-binary.x86_64-linux
nix build -f release.nix cardano-crypto.x86_64-linux
nix build -f release.nix cardano-prelude.x86_64-linux
```

should build the respective versions for each system.

### CODE REVIEW

**Comment by angerman** [comment]
Note: I'm planing to experiment with the cross compilation (linux/darwin -> windows) logic here.

**Comment by angerman** [comment]
Note2: this requires angerman/nix-tools#8 to support the used `snapshot.yaml` when using `stack-to-nix`.

**Comment by ruhatch** [comment]
@angerman What is the state of this work? We'd definitely want to see nix integration with the project, so what are the simplest steps to get that going?

**Comment by angerman** [comment]
@ruhatch sorry, completely missed that. I'll look into this today.

**Comment by angerman** [comment]
@ruhatch I'll fix the remaining issues.

**Comment by commandodev** [comment]
@angerman can we fix the conflict so that we can look at getting this merged again?

**Comment by dnadales** [comment]
@angerman any update on this PR? Do we still want to merge it?

**Pull request closed without merging**
