### PR TITLE
787 test with invalid block sizes

### PR DESCRIPTION
**Pull request by dnadales**
Part of https://github.com/input-output-hk/cardano-ledger-specs/issues/787

### CODE REVIEW

**Comment by mhuesch** [comment]
@dnadales should we have been requested as reviewers instead of added as assignees? 🙂

**Comment by dnadales** [comment]
> @dnadales should we have been requested as reviewers instead of added as assignees? slightly_smiling_face

Ups. Thanks for the heads up!

**Review by intricate — APPROVED** [review]
This LGTM :100:

**Pull request merged**
