### PR TITLE
Update `cardano-shell`, plus small Nix changes

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Review by erikd — CHANGES_REQUESTED** [review]
Can we squash all the Nix related commits into a single one?

**Comment by deepfire** [comment]
> Can we squash all the Nix related commits into a single one?

@erikd, done.

**Review by erikd — APPROVED** [review]

**Comment by erikd** [comment]
Would still be nice to clean up the `RecordWildCard` related commit (ie squash it into one one the others)

**Comment by deepfire** [comment]
Done as well!

**Pull request merged**
