### PR TITLE
Chain stats `ts_prop_generatedChainsAreValidated`

### PR DESCRIPTION
**Pull request by edsko**
Also point to latest `cardano-ledger-specs` (https://github.com/input-output-hk/cardano-ledger-specs/pull/1177).

### CODE REVIEW

**Review by dnadales — APPROVED** [review]

**Review by intricate — APPROVED** [review]

**Comment by nc6** [comment]
I've pulled the useful bits of this into #736, so if that merges we can close this.

**Comment by nc6** [comment]
Closing this since we merged #736

**Pull request closed without merging**
