### PR TITLE
Remove the specs (moving to fm-ledger-rules)

### PR DESCRIPTION
**Pull request by nc6**

### CODE REVIEW

**Review by dnadales — COMMENTED** [review]
Err... I'm working on these files at the moment. What should I do, point my remote to `fm-ledger-rules`? 

And are we able to publish the `fm-ledger-rules` on hydra yet? If not we might want to wait till that's done...

**Comment by JaredCorduan** [comment]
> Err... I'm working on these files at the moment. What should I do, point my remote to `fm-ledger-rules`?
> 
> And are we able to publish the `fm-ledger-rules` on hydra yet? If not we might want to wait till that's done...

oh, sorry @dnadales! We can wait until you are ready.  We do not have hydra yet.  We can also wait to merge my [PR](https://github.com/input-output-hk/fm-ledger-rules/pull/236) in fm-ledger rules until you are ready.

**Comment by dnadales** [comment]
> oh, sorry @dnadales! We can wait until you are ready. We do not have hydra yet. We can also wait to merge my [PR](https://github.com/input-output-hk/fm-ledger-rules/pull/236) in fm-ledger rules until you are ready.

No problem! I just spoke with @nc6. It seems that I would have to apply the diffs manually. However I hope I don't have too many changes in the `specs` directory.

**Review by ruhatch — APPROVED** [review]
LGTM! If it passes CI, I'll believe all is well!

**Comment by nc6** [comment]
bors try

**Pull request merged**
