### PR TITLE
Update stack/cabal to lts-13.24/ghc-8.6.5

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Review by ruhatch — APPROVED** [review]
LGTM!

**Review by nc6 — APPROVED** [review]

**Comment by angerman** [comment]
Let's see if we are happy with ghc865 now.

**Comment by angerman** [comment]
Rebased onto master.

**Comment by angerman** [comment]
There is only one failure left, which is one test that fails on windows (cross compiled / wine).

https://hydra.iohk.io/jobset/Cardano/cardano-ledger-pr-546#tabs-jobs

As such, I'd argue this PR is ready to merge now.

**Pull request merged**
