### PR TITLE
[#537] Add headerHashAnnotated

### LINKED ISSUE #537: Add hashHeaderAnnotated
## Background

We have blockHashAnnotated, but no corresponding headerHashAnnotated.

## Proposed Solution

Add `headerHashAnnotated :: AHeader ByteString -> HeaderHash`.

### PR DESCRIPTION
**Pull request by ruhatch**
Closes #537

### CODE REVIEW

**Review by mhuesch — APPROVED** [review]
Looks reasonable, but the diffstat comes out to +4 😜

**Comment by ruhatch** [comment]
> Looks reasonable, but the diffstat comes out to +4 stuck_out_tongue_winking_eye

Don't worry, I've got some changes coming that should be in the minus!

**Comment by mhuesch** [comment]
> Don't worry, I've got some changes coming that should be in the minus!

Heh, I figured as much 🙌

**Pull request merged**
