### PR TITLE
Add Buildkite CI

### PR DESCRIPTION
**Pull request by rvl**
This adds a Buildkite pipeline which does a stack build and test.

The GitHub repo needs to be public for Buildkite to be able to check out the source code.

### CODE REVIEW

**Comment by dnadales** [comment]
I started to see the failed buildkite builds on my PR, nice :) Do you know who should I ask to create a buildkite account?

**Comment by rvl** [comment]
Hi @dnadales, there are instructions for logging in to buildkite here: https://github.com/input-output-hk/internal-documentation/wiki/Services#buildkite
The failed builds are because buildkite doesn't have access because this repository is still private.

**Comment by dnadales** [comment]
Great. Thanks.

**Comment by mdimjasevic** [comment]
@rvl, this repository is public now. PR builds are nevertheless failing. Are these failures related to your PR? For example, my PR https://github.com/input-output-hk/cardano-chain/pull/42 is failing and reporting weird conflicts that I can't confirm locally. It would be great to resolve this soon so we can proceed with our work.

**Review by cleverca22 — APPROVED** [review]

**Pull request merged**
