### PR TITLE
[#27] Safely remove Boundary blocks

### PR DESCRIPTION
**Pull request by ruhatch**
Remove boundary blocks, using a `Dropper` to decode ones from the Byron blockchain. Once they are removed the `GenericBlock` becomes obsolete, so we can simplify all the block types a lot.

### CODE REVIEW

**Comment by nc6** [comment]
The changes here look reasonable; however, I'm not certain that it's plausible to do this. While boundary blocks are not distributed, they are concretely a part of the blockchain: their hashes are used as the parent hash for subsequent blocks. If we drop them entirely, then the chain will not be valid by the most basic of validation semantics (unless we explicitly drop this rule).

Maybe we should discuss this more widely.

**Comment by nc6** [comment]
Answered in meeting :-)

**Comment by erikd** [comment]
> Answered in meeting :-)

@nc6 And the answer was?

**Comment by erikd** [comment]
> Answered in meeting :-)

@nc6 And the answer was?

**Review by nc6 — APPROVED** [review]

**Review by nc6 — APPROVED** [review]

**Comment by nc6** [comment]
@erikd A few options: either we overhaul the validator to make it operate over the parse structure (since it can then peek back to the underlying bytestring), or support a "trees that grow" like structure, where we map over the structure to pull in the raw bytestrings. I think there is a fair bit of detail to work out here, but I was reassured that this is at least understood and there is some plan in place.

**Comment by ruhatch** [comment]
@erikd @nc6 Alex and I discussed this further and hope to return a data structure plus annotations that would contain hashes for validation. So a `Decoder s (Annotated Hash ())`  for boundary blocks and a `Decoder s (Annotated BlockValidationData Block)` for normal blocks.

**Pull request merged**
